import { Inter } from "next/font/google";
import "./globals.css";
import '../styles/uswds.css'
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       {/* <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
          <title>Tec Project</title>
          <script src= '../node_modules/uswds/dist/js/uswds-init.min.js'></script>
      </head> */}

      <body className={inter.className}>{children}</body>
    </html>
  );
}
